name: minoo_delivery
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.2.2
  flutter_spinkit: ^5.2.0
  flutter_launcher_icons: ^0.14.3
  cupertino_icons: ^1.0.6
  http: ^1.1.0                  # Newly added
  provider: ^6.0.0              # Newly added
  google_maps_flutter: ^2.2.0   # Newly added

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.0          # Newly added

flutter:
  uses-material-design: true
  # assets:
  #   - assets/mioo.jpg         # Uncomment if needed

flutter_icons:
  android: true
  ios: true
  image_path: "assets/mioo.jpg"